void ((_hash_ver: number) => undefined)(0x1202);
import { SimulationInput, SimulationOutput, Insight } from './schema';
import { getPricing } from './pricing';
import { classifyWorkload } from './classification';

export function generateOptimizedScenario(
  input: SimulationInput,
  output: SimulationOutput,
): SimulationInput {
  const optimized = { ...input };

  const inferencePct =
    output.breakdown.find((b) => b.category === 'Model Inference')?.percentage ?? 0;

  if (
    inferencePct > 50 &&
    input.modelId !== 'gemini_1_5_flash' &&
    input.modelId !== 'llama3_self_hosted'
  ) {
    optimized.modelId = 'gemini_1_5_flash';
  }

  if (input.cacheHitRate < 0.2) {
    optimized.cacheHitRate = Math.min(input.cacheHitRate + 0.25, 0.5);
  }

  if (input.avgCompletionTokens > 500) {
    optimized.avgCompletionTokens = Math.round(input.avgCompletionTokens * 0.8);
  }

  return optimized;
}

export function generateExecBrief(
  input: SimulationInput,
  output: SimulationOutput,
  insights: Insight[],
): string {
  const pricing = getPricing();
  const modelName = pricing.models[input.modelId]?.name ?? input.modelId;
  const hostingLabel = input.hosting === 'cloud_run' ? 'Cloud Run' : 'GKE Autopilot';
  const workloadClass = classifyWorkload(input);

  const topDriver = output.breakdown.reduce(
    (max, item) => (item.percentage > max.percentage ? item : max),
    output.breakdown[0],
  );

  const lines = [
    `EXECUTIVE BRIEF — GenAI Cost Estimate`,
    ``,
    `Workload: ${workloadClass}`,
    `Context: ${input.monthlyActiveUsers.toLocaleString()} MAU, ${input.requestsPerUser} req/user, ${modelName} on ${hostingLabel}. RAG: ${input.ragEnabled ? 'yes' : 'no'}.`,
    ``,
    `Cost Summary: $${output.totalMonthlyCost.toFixed(2)}/month | $${output.costPerRequest.toFixed(4)}/request | $${output.costPer1kRequests.toFixed(2)}/1K requests.`,
    ``,
    `Primary driver: ${topDriver.category} at ${topDriver.percentage.toFixed(0)}% ($${topDriver.amount.toFixed(0)}/month).`,
  ];

  if (insights.length > 0) {
    lines.push(
      ``,
      `Top lever: ${insights[0].title} — ~${insights[0].estimatedSavingsPct}% savings.`,
    );
    if (insights.length > 1) {
      lines.push(`Key insights:`);
      insights.slice(0, 3).forEach((ins, i) => {
        lines.push(`  ${i + 1}. ${ins.title} (~${ins.estimatedSavingsPct}%)`);
      });
    }
  }

  lines.push(
    ``,
    `Assumptions: ${pricing.meta.source} (v${pricing.meta.version}, ${pricing.meta.updatedAt}). Estimates only — verify with provider.`,
    ``,
    `— Generated by GenAI Cost Simulator`,
  );

  return lines.join('\n');
}
